config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'courses/new', to:'courses#new'
  get 'about', to:'pages#about'
  resources :students 
  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  get 'logout', to:'sessions#destroy'
  post 'course_enroll', to:'student_courses#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 26 }
    validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
    validates :description, presence: true, length: { minimum: 3, maximum: 100 }
    has_many :student_courses
    has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord 
    before_save { self.email= email.downcase }
    validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {minimum:3,maximum:26}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum:200},
    format: {with: VALID_EMAIL_REGEX}
     
    has_secure_password

    has_many :student_courses
    has_many :courses, through: :student_courses
end 

app/models/student_course.rb
class StudentCourse < ApplicationRecord
belongs_to :student
belongs_to :course

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||=Student.find(session[:student_id] ) if session[:student_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:notice]="You need to login first before doing this action"
        end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    def index
        @courses=Course.all
    end

    def new

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create 

        student=Student.find_by(email: params[:sessions][:email] )
        if student && student.authenticate(params[:sessions][:password])
            session[:student_id]=student.id
            flash[:notice]="successfully logged in"
            redirect_to student
        else
            flash.now[:notice]="something was wrong with your information"
            render 'new'
        end

    end

    def destroy
        session[:student_id]=nil
        flash[:notice]="logged out successfuly"
        redirect_to root_path
    end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController

    def create
        course_to_add = Course.find(params[:course_id])

        unless current_user.courses.include?(course_to_add)
          StudentCourse.create(course: course_to_add, student: current_user)
          flash[:notice] = "You have successfully enrolled in #{course_to_add.name}"
          redirect_to current_user
        else
          flash[:notice] = "Something was wrong with your enrollment"
          redirect_to root_path
        end
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :require_user, only:[:edit,:update]
    before_action :require_same_user, only:[:edit,:update]
    def show 
        @student=Student.find(params[:id])
    end
    def index
        @students=Student.all
    end
    def new 
        @student=Student.new
    end

    def edit 
        @student=Student.find(params[:id])
    end
    def create 
        @student=Student.new(params.require(:student).permit(:name, :email, :password, :confirm_password))
        if @student.save
            flash[:notice]="Student created successfully"
            redirect_to students_path
        else
            render 'new'
        end
    end
    def update 
        @student=Student.find(params[:id])
       if @student.update(params.require(:student).permit(:name, :email, :password, :password_confirmation))
            flash[:notice]="Successfully updated"
            redirect_to @student
        else
            render 'edit'
        end
    end

    private
    def require_same_user
        @student=Student.find(params[:id])
        if current_user.id !=@student.id
            flash[:notice]="you are not allowed for this action"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<div class="row">
    <div class="col s12 ">
        <h3 class="center-align">Course listing</h3>
    </div>
</div>

<div class="row">
<% @courses.each do |course| %>
    <div class="col s6 m6">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
                <p><%= course.description %></p>
            </div>
    <div class="card-action">
    <% if logged_in? && !(current_user.courses.include?(course)) %>
        <%= link_to "Enroll", course_enroll_path(course_id: course.id), method: :post %>
    <% end %>  
      <a href="#">info</a>
    </div>
  </div>
</div>

<% end %>
</div>

app/views/courses/new.html.erb
<h1>new course</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
<div class="container">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">Tech university</h5>
      <p class="grey-text text-lighten-4">A program for developement.</p>
    </div>
    <div class="col l4 offset-l2 s12">
      
      <ul>
        <li><a class="grey-text text-lighten-3" href="#!">Help </a></li>
        <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
        <li><a class="grey-text text-lighten-3" href="#!">Contact us 3</a></li>
      
      </ul>
    </div>
  </div>
</div>
<div class="footer-copyright">
  <div class="container">
  © 2022 Tech University

  </div>
</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
<ul id="dropdown1" class="dropdown-content">
<% if logged_in? %>
  <li><%= link_to "log out", logout_path %></li>
  <li><%= link_to "Profile", student_path(current_user) %></li>
<% else %>
<li><%= link_to "log in", login_path %></li>
<li><%= link_to "Sign up", new_student_path %></li>
<% end %>
  
</ul>
<ul id="dropdown2" class="dropdown-content">
  <% if logged_in? %>
  <li><%= link_to "log out", logout_path %></li>
  <li><%= link_to "Profile", student_path(current_user) %></li>
  <% else %>
  <li><%= link_to "log in", login_path %></li>
  <li><%= link_to "Sign up", new_student_path %></li>
  <% end %>
 
</ul>
<nav>
<div class="container">
  <div class="nav-wrapper">
    <a href="#" class="brand-logo right">Tech University</a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul id="nav-mobile" class="left hide-on-med-and-down">
      <li><%= link_to "Courses", root_path %></li>
      <% if logged_in? %>
      <li><%= link_to "Students", students_path %></li>
      <% end %>
      <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Acount<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
    <ul class="sidenav" id="mobile-demo">
    <li><%= link_to "Courses", root_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Students", students_path %></li>
    <% end %>
    <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Acount<i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>
          
  </div>
</div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S12ProjectAppRails5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'layouts/navbar'%>

  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row sign-up-form">
        <div class="col s12 m12 l12">
          <div class="card-panel green lighten-2" id="fade-out">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <main>
    <div class="container">
      <%= yield %>
    </div>
  </main>  
  <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>welcome to about page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong>
                <%= pluralize(obj.errors.count, "error") %>
              prohibited your profile from being created
            </strong>
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj:@student %>

<div class="containter">
  <div class="row center">
    <div class="col s12 m12 l12">
      <div class="card-panel signup">
        <div class="row">
          <h4 class="header"><%= @student.new_record? ? "Signup" : "Submit Updates" %></h4>
            <%= form_for(@student, html: {class: "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :name, class: "active" %>
                <%= f.text_field :name, placeholder:"Enter your name" %>
              </div>
            </div>    
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :eamil, class: "active" %>
                <%= f.text_field :email, placeholder:"Enter your email" %>
              </div>
            </div> 
            <div class="row">
            <div class="input-field col s12">
              <%= f.label :password, class: "active" %>
              <%= f.password_field :password, placeholder:"Enter your password" %>
            </div>
            </div> 

            <div class="row">
            <div class="input-field col s12">
              <%= f.label :password_confirmation, class: "active" %>
              <%= f.password_field :password_confirmation, placeholder:"Confirm password" %>
            </div>
            </div> 

            <div class="row">
            <div class="col s12">
              <%= f.button class: "waves-effect waves-light btn" %>
            </div>
            </div>

            <% end %>

          </div>
        </div>
      </div>
    </div>
</div>
  
  

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
    <div class="col s12 ">
        <h3 class="center-align">Student listing</h3>
    </div>
</div>

<div class="row">
<% @students.each do |student| %>
    <div class="col s6 m6">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title"><%= student.name %> </span>
                <span class="card-title"><%= student.email %> </span>
                <p> Enrollments:
                <% if student.courses.empty? %>
                none
                <% else %>
                    <% student.courses.each do |course| %>
                        <%= course.name %>
                    <% end %>
                <% end %> 
                </p>
            </div>
    <div class="card-action">
      <%= link_to "View Profile", student_path(student) %>
    </div>
  </div>
</div>

<% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row">
    <div class="col s12 ">
        <h3 class="center-align">Student Show Page</h3>
    </div>
</div>

<div class="row">

    <div class="col s6 m6">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title"><%= @student.name %> </span>
                <span class="card-title"><%= @student.email %> </span>
                <p> Enrollments:
                <% if @student.courses.empty? %>
                none 
                <% else %>
                    <% @student.courses.each do |course| %>
                       <ul> <li><%= course.name %></li> </ul>
                    <% end %>
                <% end %>    
                </p>
            </div>
    
         </div>
         <% if logged_in? && current_user.id==@student.id %>
         <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
         <% end %>
    </div>

   
</div>